
replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1.3"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

keycloak:
  adminUser: admin
  adminPassword: admin
  proxy: edge
  proxyAddressForwarding: "true"
  extraArgs: ["start-dev"]

namespace: keycloak